# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QTextEdit, QToolBar, QVBoxLayout,
    QWidget)

from pyqtgraph import PlotWidget
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1290, 922)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        iconThemeName = u"application-x-executable"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.970000000000000)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon1 = QIcon()
        icon1.addFile(u":/images/quitIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon2 = QIcon()
        icon2.addFile(u":/images/copyIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon2)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon3 = QIcon()
        icon3.addFile(u":/images/cutIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon3)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon4 = QIcon()
        icon4.addFile(u":/images/pasteIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon4)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon5 = QIcon()
        icon5.addFile(u":/images/undoIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon5)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon6 = QIcon()
        icon6.addFile(u":/images/redoIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon6)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon7 = QIcon()
        icon7.addFile(u":/images/aboutIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAboutQt = QAction(MainWindow)
        self.actionAboutQt.setObjectName(u"actionAboutQt")
        icon8 = QIcon()
        icon8.addFile(u":/images/aboutQtIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAboutQt.setIcon(icon8)
        self.actionOperator = QAction(MainWindow)
        self.actionOperator.setObjectName(u"actionOperator")
        self.actiontechnic = QAction(MainWindow)
        self.actiontechnic.setObjectName(u"actiontechnic")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionView = QAction(MainWindow)
        self.actionView.setObjectName(u"actionView")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabTesting = QWidget()
        self.tabTesting.setObjectName(u"tabTesting")
        self.frame = QFrame(self.tabTesting)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 271, 771))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.tabInputs = QTabWidget(self.frame)
        self.tabInputs.setObjectName(u"tabInputs")
        self.tabInputs.setGeometry(QRect(10, 110, 251, 371))
        self.InputStep1 = QWidget()
        self.InputStep1.setObjectName(u"InputStep1")
        self.frame_4 = QFrame(self.InputStep1)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 0, 221, 341))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_2 = QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 29, 201, 291))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(u"label")

        self.verticalLayout_3.addWidget(self.label)

        self.operatorName = QLineEdit(self.verticalLayoutWidget_2)
        self.operatorName.setObjectName(u"operatorName")

        self.verticalLayout_3.addWidget(self.operatorName)

        self.label_2 = QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout_3.addWidget(self.label_2)

        self.operatorCode = QLineEdit(self.verticalLayoutWidget_2)
        self.operatorCode.setObjectName(u"operatorCode")

        self.verticalLayout_3.addWidget(self.operatorCode)

        self.label_9 = QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(u"label_9")

        self.verticalLayout_3.addWidget(self.label_9)

        self.workOrder = QLineEdit(self.verticalLayoutWidget_2)
        self.workOrder.setObjectName(u"workOrder")

        self.verticalLayout_3.addWidget(self.workOrder)

        self.label_6 = QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")

        self.verticalLayout_3.addWidget(self.label_6)

        self.serialNumber = QLineEdit(self.verticalLayoutWidget_2)
        self.serialNumber.setObjectName(u"serialNumber")
        self.serialNumber.setStyleSheet(u"background-color: rgb(255, 255, 255);")

        self.verticalLayout_3.addWidget(self.serialNumber)

        self.tabInputs.addTab(self.InputStep1, "")
        self.InputStep2 = QWidget()
        self.InputStep2.setObjectName(u"InputStep2")
        self.frame_9 = QFrame(self.InputStep2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(10, 20, 221, 261))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.lineEdit_3 = QLineEdit(self.frame_9)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 70, 201, 21))
        self.label_10 = QLabel(self.frame_9)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 200, 199, 21))
        self.tabInputs.addTab(self.InputStep2, "")
        self.InputStep3 = QWidget()
        self.InputStep3.setObjectName(u"InputStep3")
        self.tabInputs.addTab(self.InputStep3, "")
        self.InputStep4 = QWidget()
        self.InputStep4.setObjectName(u"InputStep4")
        self.tabInputs.addTab(self.InputStep4, "")
        self.InputStep5 = QWidget()
        self.InputStep5.setObjectName(u"InputStep5")
        self.tabInputs.addTab(self.InputStep5, "")
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 10, 251, 91))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 0, 211, 91))
        self.label_3.setStyleSheet(u"image: url(:/images/logo.png);")
        self.frame_11 = QFrame(self.frame)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(10, 490, 251, 271))
        self.frame_11.setStyleSheet(u"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.technicianControls = QTabWidget(self.frame_11)
        self.technicianControls.setObjectName(u"technicianControls")
        self.technicianControls.setGeometry(QRect(10, 10, 231, 251))
        self.technicianControls.setStyleSheet(u"background-color: rgb(200, 195, 196);")
        self.canCommands = QWidget()
        self.canCommands.setObjectName(u"canCommands")
        self.canCommand1 = QPushButton(self.canCommands)
        self.canCommand1.setObjectName(u"canCommand1")
        self.canCommand1.setGeometry(QRect(20, 40, 191, 24))
        self.canCommand2 = QPushButton(self.canCommands)
        self.canCommand2.setObjectName(u"canCommand2")
        self.canCommand2.setGeometry(QRect(20, 70, 191, 24))
        self.canCommand3 = QPushButton(self.canCommands)
        self.canCommand3.setObjectName(u"canCommand3")
        self.canCommand3.setGeometry(QRect(20, 100, 191, 24))
        self.canCommand4 = QPushButton(self.canCommands)
        self.canCommand4.setObjectName(u"canCommand4")
        self.canCommand4.setGeometry(QRect(20, 130, 191, 24))
        self.technicianControls.addTab(self.canCommands, "")
        self.sshCommands = QWidget()
        self.sshCommands.setObjectName(u"sshCommands")
        self.plainTextEdit = QPlainTextEdit(self.sshCommands)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 20, 201, 191))
        self.plainTextEdit.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.technicianControls.addTab(self.sshCommands, "")
        self.frame_2 = QFrame(self.tabTesting)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(290, 10, 641, 761))
        self.frame_2.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.ButtonNext = QPushButton(self.frame_2)
        self.ButtonNext.setObjectName(u"ButtonNext")
        self.ButtonNext.setGeometry(QRect(490, 680, 111, 61))
        self.ButtonQuit = QPushButton(self.frame_2)
        self.ButtonQuit.setObjectName(u"ButtonQuit")
        self.ButtonQuit.setGeometry(QRect(20, 680, 101, 51))
        self.frame_8 = QFrame(self.frame_2)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 621, 401))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.tabInstructions = QTabWidget(self.frame_8)
        self.tabInstructions.setObjectName(u"tabInstructions")
        self.tabInstructions.setGeometry(QRect(20, 10, 601, 371))
        self.tabInstructions.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.InstructionStep1 = QWidget()
        self.InstructionStep1.setObjectName(u"InstructionStep1")
        self.groupBox = QGroupBox(self.InstructionStep1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(40, 40, 511, 231))
        self.groupBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabInstructions.addTab(self.InstructionStep1, "")
        self.InstructionStep2 = QWidget()
        self.InstructionStep2.setObjectName(u"InstructionStep2")
        self.label_7 = QLabel(self.InstructionStep2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 30, 289, 229))
        self.label_7.setStyleSheet(u"image: url(:/images/test1.png);")
        self.tabInstructions.addTab(self.InstructionStep2, "")
        self.InstructionStep3 = QWidget()
        self.InstructionStep3.setObjectName(u"InstructionStep3")
        self.label_8 = QLabel(self.InstructionStep3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 40, 271, 231))
        self.label_8.setStyleSheet(u"image: url(:/images/test2.png);")
        self.tabInstructions.addTab(self.InstructionStep3, "")
        self.InstructionStep4 = QWidget()
        self.InstructionStep4.setObjectName(u"InstructionStep4")
        self.graphWidget = PlotWidget(self.InstructionStep4)
        self.graphWidget.setObjectName(u"graphWidget")
        self.graphWidget.setGeometry(QRect(30, 50, 521, 251))
        self.tabInstructions.addTab(self.InstructionStep4, "")
        self.InstructionStep5 = QWidget()
        self.InstructionStep5.setObjectName(u"InstructionStep5")
        self.startButton = QPushButton(self.InstructionStep5)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(240, 310, 75, 24))
        self.colorText = QTextEdit(self.InstructionStep5)
        self.colorText.setObjectName(u"colorText")
        self.colorText.setGeometry(QRect(350, 310, 221, 21))
        self.colorText.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabInstructions.addTab(self.InstructionStep5, "")
        self.frame_7 = QFrame(self.frame_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 460, 621, 211))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_7)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 10, 91, 16))
        self.label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.InstructionsText = QTextEdit(self.frame_7)
        self.InstructionsText.setObjectName(u"InstructionsText")
        self.InstructionsText.setGeometry(QRect(30, 30, 281, 141))
        self.InstructionsText.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.frame_7)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(330, 10, 151, 16))
        self.label_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.InstructionsText_2 = QTextEdit(self.frame_7)
        self.InstructionsText_2.setObjectName(u"InstructionsText_2")
        self.InstructionsText_2.setGeometry(QRect(330, 30, 281, 141))
        self.InstructionsText_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.horizontalLayoutWidget = QWidget(self.frame_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(30, 430, 601, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.passButton = QPushButton(self.horizontalLayoutWidget)
        self.passButton.setObjectName(u"passButton")
        self.passButton.setStyleSheet(u"background-color: rgb(0, 255, 0);")

        self.horizontalLayout_2.addWidget(self.passButton)

        self.failButton = QPushButton(self.horizontalLayoutWidget)
        self.failButton.setObjectName(u"failButton")
        self.failButton.setStyleSheet(u"background-color: rgb(255, 0, 0);")

        self.horizontalLayout_2.addWidget(self.failButton)

        self.repeatButton = QPushButton(self.frame_2)
        self.repeatButton.setObjectName(u"repeatButton")
        self.repeatButton.setGeometry(QRect(360, 680, 111, 61))
        self.frame_3 = QFrame(self.tabTesting)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(940, 10, 301, 761))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.tabOutputs = QTabWidget(self.frame_3)
        self.tabOutputs.setObjectName(u"tabOutputs")
        self.tabOutputs.setGeometry(QRect(10, 30, 281, 401))
        self.OutputStep1 = QWidget()
        self.OutputStep1.setObjectName(u"OutputStep1")
        self.frame_6 = QFrame(self.OutputStep1)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 20, 251, 341))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.tabOutputs.addTab(self.OutputStep1, "")
        self.OutputStep2 = QWidget()
        self.OutputStep2.setObjectName(u"OutputStep2")
        self.tabOutputs.addTab(self.OutputStep2, "")
        self.OutputStep3 = QWidget()
        self.OutputStep3.setObjectName(u"OutputStep3")
        self.tabOutputs.addTab(self.OutputStep3, "")
        self.OutputStep4 = QWidget()
        self.OutputStep4.setObjectName(u"OutputStep4")
        self.tabOutputs.addTab(self.OutputStep4, "")
        self.OutputStep5 = QWidget()
        self.OutputStep5.setObjectName(u"OutputStep5")
        self.tabOutputs.addTab(self.OutputStep5, "")
        self.frame_10 = QFrame(self.frame_3)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 450, 281, 301))
        self.frame_10.setStyleSheet(u"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.technicianView = QTabWidget(self.frame_10)
        self.technicianView.setObjectName(u"technicianView")
        self.technicianView.setGeometry(QRect(10, 10, 261, 281))
        self.technicianView.setStyleSheet(u"background-color: rgb(200, 195, 196);")
        self.tabCanOutput = QWidget()
        self.tabCanOutput.setObjectName(u"tabCanOutput")
        self.frame_14 = QFrame(self.tabCanOutput)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(10, 140, 241, 80))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.d2Output = QLineEdit(self.frame_14)
        self.d2Output.setObjectName(u"d2Output")
        self.d2Output.setGeometry(QRect(60, 40, 31, 21))
        self.d0Output = QLineEdit(self.frame_14)
        self.d0Output.setObjectName(u"d0Output")
        self.d0Output.setGeometry(QRect(0, 40, 31, 21))
        self.d1Output = QLineEdit(self.frame_14)
        self.d1Output.setObjectName(u"d1Output")
        self.d1Output.setGeometry(QRect(30, 40, 31, 21))
        self.d5Output = QLineEdit(self.frame_14)
        self.d5Output.setObjectName(u"d5Output")
        self.d5Output.setGeometry(QRect(150, 40, 31, 21))
        self.d4Output = QLineEdit(self.frame_14)
        self.d4Output.setObjectName(u"d4Output")
        self.d4Output.setGeometry(QRect(120, 40, 31, 21))
        self.d3Output = QLineEdit(self.frame_14)
        self.d3Output.setObjectName(u"d3Output")
        self.d3Output.setGeometry(QRect(90, 40, 31, 21))
        self.d6Output = QLineEdit(self.frame_14)
        self.d6Output.setObjectName(u"d6Output")
        self.d6Output.setGeometry(QRect(180, 40, 31, 21))
        self.d7Output = QLineEdit(self.frame_14)
        self.d7Output.setObjectName(u"d7Output")
        self.d7Output.setGeometry(QRect(210, 40, 31, 21))
        self.canIdOuput = QLineEdit(self.frame_14)
        self.canIdOuput.setObjectName(u"canIdOuput")
        self.canIdOuput.setGeometry(QRect(0, 10, 31, 21))
        self.label_12 = QLabel(self.frame_14)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 10, 199, 21))
        self.frame_13 = QFrame(self.tabCanOutput)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(10, 20, 241, 71))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.d2Input = QLineEdit(self.frame_13)
        self.d2Input.setObjectName(u"d2Input")
        self.d2Input.setGeometry(QRect(60, 40, 31, 21))
        self.d0Input = QLineEdit(self.frame_13)
        self.d0Input.setObjectName(u"d0Input")
        self.d0Input.setGeometry(QRect(0, 40, 31, 21))
        self.d1Input = QLineEdit(self.frame_13)
        self.d1Input.setObjectName(u"d1Input")
        self.d1Input.setGeometry(QRect(30, 40, 31, 21))
        self.d5Input = QLineEdit(self.frame_13)
        self.d5Input.setObjectName(u"d5Input")
        self.d5Input.setGeometry(QRect(150, 40, 31, 21))
        self.d4Input = QLineEdit(self.frame_13)
        self.d4Input.setObjectName(u"d4Input")
        self.d4Input.setGeometry(QRect(120, 40, 31, 21))
        self.d3Input = QLineEdit(self.frame_13)
        self.d3Input.setObjectName(u"d3Input")
        self.d3Input.setGeometry(QRect(90, 40, 31, 21))
        self.d6Input = QLineEdit(self.frame_13)
        self.d6Input.setObjectName(u"d6Input")
        self.d6Input.setGeometry(QRect(180, 40, 31, 21))
        self.d7Input = QLineEdit(self.frame_13)
        self.d7Input.setObjectName(u"d7Input")
        self.d7Input.setGeometry(QRect(210, 40, 31, 21))
        self.canIdInput = QLineEdit(self.frame_13)
        self.canIdInput.setObjectName(u"canIdInput")
        self.canIdInput.setGeometry(QRect(0, 10, 31, 21))
        self.label_11 = QLabel(self.frame_13)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 10, 199, 21))
        self.technicianView.addTab(self.tabCanOutput, "")
        self.tabSshOutput = QWidget()
        self.tabSshOutput.setObjectName(u"tabSshOutput")
        self.technicianView.addTab(self.tabSshOutput, "")
        self.tabWidget.addTab(self.tabTesting, "")
        self.tabData = QWidget()
        self.tabData.setObjectName(u"tabData")
        self.verticalLayout = QVBoxLayout(self.tabData)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tableTests = QTableWidget(self.tabData)
        if (self.tableTests.columnCount() < 11):
            self.tableTests.setColumnCount(11)
        font = QFont()
        font.setPointSize(8)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font);
        self.tableTests.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font);
        self.tableTests.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font);
        self.tableTests.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setFont(font);
        self.tableTests.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setFont(font);
        self.tableTests.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setFont(font);
        self.tableTests.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setFont(font);
        self.tableTests.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font);
        self.tableTests.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font);
        self.tableTests.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setFont(font);
        self.tableTests.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setFont(font);
        self.tableTests.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        self.tableTests.setObjectName(u"tableTests")
        self.tableTests.setFont(font)
        self.tableTests.setAutoFillBackground(True)
        self.tableTests.setStyleSheet(u"")
        self.tableTests.horizontalHeader().setDefaultSectionSize(120)

        self.verticalLayout.addWidget(self.tableTests)

        self.tabWidget.addTab(self.tabData, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1290, 30))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSQL_Database = QMenu(self.menubar)
        self.menuSQL_Database.setObjectName(u"menuSQL_Database")
        self.menuOperation_Mode = QMenu(self.menubar)
        self.menuOperation_Mode.setObjectName(u"menuOperation_Mode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy1)
        self.toolBar.setMovable(True)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.operatorName, self.operatorCode)
        QWidget.setTabOrder(self.operatorCode, self.lineEdit_3)
        QWidget.setTabOrder(self.lineEdit_3, self.tableTests)
        QWidget.setTabOrder(self.tableTests, self.tabInstructions)
        QWidget.setTabOrder(self.tabInstructions, self.tabOutputs)
        QWidget.setTabOrder(self.tabOutputs, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.InstructionsText_2)
        QWidget.setTabOrder(self.InstructionsText_2, self.InstructionsText)
        QWidget.setTabOrder(self.InstructionsText, self.ButtonQuit)
        QWidget.setTabOrder(self.ButtonQuit, self.failButton)
        QWidget.setTabOrder(self.failButton, self.passButton)
        QWidget.setTabOrder(self.passButton, self.ButtonNext)
        QWidget.setTabOrder(self.ButtonNext, self.tabInputs)
        QWidget.setTabOrder(self.tabInputs, self.repeatButton)
        QWidget.setTabOrder(self.repeatButton, self.technicianView)
        QWidget.setTabOrder(self.technicianView, self.technicianControls)
        QWidget.setTabOrder(self.technicianControls, self.canCommand1)
        QWidget.setTabOrder(self.canCommand1, self.canCommand2)
        QWidget.setTabOrder(self.canCommand2, self.canCommand3)
        QWidget.setTabOrder(self.canCommand3, self.canCommand4)
        QWidget.setTabOrder(self.canCommand4, self.plainTextEdit)
        QWidget.setTabOrder(self.plainTextEdit, self.d2Input)
        QWidget.setTabOrder(self.d2Input, self.d0Input)
        QWidget.setTabOrder(self.d0Input, self.d1Input)
        QWidget.setTabOrder(self.d1Input, self.d5Input)
        QWidget.setTabOrder(self.d5Input, self.d4Input)
        QWidget.setTabOrder(self.d4Input, self.d3Input)
        QWidget.setTabOrder(self.d3Input, self.d6Input)
        QWidget.setTabOrder(self.d6Input, self.d7Input)
        QWidget.setTabOrder(self.d7Input, self.canIdInput)
        QWidget.setTabOrder(self.canIdInput, self.d2Output)
        QWidget.setTabOrder(self.d2Output, self.d0Output)
        QWidget.setTabOrder(self.d0Output, self.d1Output)
        QWidget.setTabOrder(self.d1Output, self.d5Output)
        QWidget.setTabOrder(self.d5Output, self.d4Output)
        QWidget.setTabOrder(self.d4Output, self.d3Output)
        QWidget.setTabOrder(self.d3Output, self.d6Output)
        QWidget.setTabOrder(self.d6Output, self.d7Output)
        QWidget.setTabOrder(self.d7Output, self.canIdOuput)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSQL_Database.menuAction())
        self.menubar.addAction(self.menuOperation_Mode.menuAction())
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuSQL_Database.addSeparator()
        self.menuSQL_Database.addAction(self.actionExport)
        self.menuSQL_Database.addAction(self.actionImport)
        self.menuSQL_Database.addSeparator()
        self.menuSQL_Database.addAction(self.actionView)
        self.menuOperation_Mode.addAction(self.actionOperator)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabInputs.setCurrentIndex(0)
        self.technicianControls.setCurrentIndex(0)
        self.tabInstructions.setCurrentIndex(4)
        self.tabOutputs.setCurrentIndex(0)
        self.technicianView.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Midmark Sterilizer test system V1.0", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAboutQt.setText(QCoreApplication.translate("MainWindow", u"AboutQt", None))
        self.actionOperator.setText(QCoreApplication.translate("MainWindow", u"Operator", None))
        self.actiontechnic.setText(QCoreApplication.translate("MainWindow", u"technic", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(shortcut)
        self.actionView.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+V", None))
#endif // QT_CONFIG(shortcut)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Operator", None))
        self.operatorName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fill your name", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Code", None))
        self.operatorCode.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fill your name", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Work Order", None))
        self.workOrder.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fill work order", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Serial Number UUT", None))
        self.serialNumber.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fill serial Number", None))
        self.tabInputs.setTabText(self.tabInputs.indexOf(self.InputStep1), QCoreApplication.translate("MainWindow", u"InputStep1", None))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fill Serial Number UUT", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Serial Number", None))
        self.tabInputs.setTabText(self.tabInputs.indexOf(self.InputStep2), QCoreApplication.translate("MainWindow", u"InputStep2", None))
        self.tabInputs.setTabText(self.tabInputs.indexOf(self.InputStep3), QCoreApplication.translate("MainWindow", u"InputStep3", None))
        self.tabInputs.setTabText(self.tabInputs.indexOf(self.InputStep4), QCoreApplication.translate("MainWindow", u"InputStep4", None))
        self.tabInputs.setTabText(self.tabInputs.indexOf(self.InputStep5), QCoreApplication.translate("MainWindow", u"InputStep5", None))
        self.label_3.setText("")
        self.canCommand1.setText(QCoreApplication.translate("MainWindow", u"CAN command 1", None))
        self.canCommand2.setText(QCoreApplication.translate("MainWindow", u"CAN command 2", None))
        self.canCommand3.setText(QCoreApplication.translate("MainWindow", u"CAN command 3", None))
        self.canCommand4.setText(QCoreApplication.translate("MainWindow", u"CAN command 4", None))
        self.technicianControls.setTabText(self.technicianControls.indexOf(self.canCommands), QCoreApplication.translate("MainWindow", u"CAN", None))
        self.technicianControls.setTabText(self.technicianControls.indexOf(self.sshCommands), QCoreApplication.translate("MainWindow", u"SSH", None))
        self.ButtonNext.setText(QCoreApplication.translate("MainWindow", u"NEXT", None))
        self.ButtonQuit.setText(QCoreApplication.translate("MainWindow", u"QUIT", None))
        self.groupBox.setTitle("")
        self.tabInstructions.setTabText(self.tabInstructions.indexOf(self.InstructionStep1), QCoreApplication.translate("MainWindow", u"InstructionStep1", None))
        self.label_7.setText("")
        self.tabInstructions.setTabText(self.tabInstructions.indexOf(self.InstructionStep2), QCoreApplication.translate("MainWindow", u"InstructionStep2", None))
        self.label_8.setText("")
        self.tabInstructions.setTabText(self.tabInstructions.indexOf(self.InstructionStep3), QCoreApplication.translate("MainWindow", u"InstructionStep3", None))
        self.tabInstructions.setTabText(self.tabInstructions.indexOf(self.InstructionStep4), QCoreApplication.translate("MainWindow", u"InstructionStep4", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"start", None))
        self.tabInstructions.setTabText(self.tabInstructions.indexOf(self.InstructionStep5), QCoreApplication.translate("MainWindow", u"InstructionStep5", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Instructions", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Comments for test", None))
        self.passButton.setText(QCoreApplication.translate("MainWindow", u"PASS", None))
        self.failButton.setText(QCoreApplication.translate("MainWindow", u"FAIL", None))
        self.repeatButton.setText(QCoreApplication.translate("MainWindow", u"REPEAT", None))
        self.tabOutputs.setTabText(self.tabOutputs.indexOf(self.OutputStep1), QCoreApplication.translate("MainWindow", u"OutputStep1", None))
        self.tabOutputs.setTabText(self.tabOutputs.indexOf(self.OutputStep2), QCoreApplication.translate("MainWindow", u"OutputStep2", None))
        self.tabOutputs.setTabText(self.tabOutputs.indexOf(self.OutputStep3), QCoreApplication.translate("MainWindow", u"OutputStep3", None))
        self.tabOutputs.setTabText(self.tabOutputs.indexOf(self.OutputStep4), QCoreApplication.translate("MainWindow", u"OutputStep4", None))
        self.tabOutputs.setTabText(self.tabOutputs.indexOf(self.OutputStep5), QCoreApplication.translate("MainWindow", u"OutputStep5", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"CAN output", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"CAN input", None))
        self.technicianView.setTabText(self.technicianView.indexOf(self.tabCanOutput), QCoreApplication.translate("MainWindow", u"CAN Messages", None))
        self.technicianView.setTabText(self.technicianView.indexOf(self.tabSshOutput), QCoreApplication.translate("MainWindow", u"SSH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTesting), QCoreApplication.translate("MainWindow", u"Testing System", None))
        ___qtablewidgetitem = self.tableTests.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Operator", None));
        ___qtablewidgetitem1 = self.tableTests.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Operator_Code", None));
        ___qtablewidgetitem2 = self.tableTests.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Serial_Number", None));
        ___qtablewidgetitem3 = self.tableTests.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Work_Order", None));
        ___qtablewidgetitem4 = self.tableTests.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"photo", None));
        ___qtablewidgetitem5 = self.tableTests.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Time", None));
        ___qtablewidgetitem6 = self.tableTests.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem7 = self.tableTests.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Step 2.CAN_bus ", None));
        ___qtablewidgetitem8 = self.tableTests.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Step 3.Touch_Screen", None));
        ___qtablewidgetitem9 = self.tableTests.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Step 4.RGB_on_LCD", None));
        ___qtablewidgetitem10 = self.tableTests.horizontalHeaderItem(10)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Comments", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), QCoreApplication.translate("MainWindow", u"Data", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuSQL_Database.setTitle(QCoreApplication.translate("MainWindow", u"SQL Database", None))
        self.menuOperation_Mode.setTitle(QCoreApplication.translate("MainWindow", u"Operation Mode", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

