# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTimeEdit,
    QToolBar, QVBoxLayout, QWidget)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModal)
        MainWindow.resize(1442, 879)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon = QIcon()
        icon.addFile(u":/images/aboutQtIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon)
        self.actionopen = QAction(MainWindow)
        self.actionopen.setObjectName(u"actionopen")
        icon1 = QIcon()
        icon1.addFile(u":/images/pasteIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionopen.setIcon(icon1)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u":/images/copyIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOperator = QAction(MainWindow)
        self.actionOperator.setObjectName(u"actionOperator")
        self.actionOperator.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/images/aboutIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOperator.setIcon(icon3)
        self.actionTechnician = QAction(MainWindow)
        self.actionTechnician.setObjectName(u"actionTechnician")
        self.actionTechnician.setCheckable(True)
        self.actionTechnician.setIcon(icon)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon4 = QIcon()
        icon4.addFile(u":/images/quitIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 20, 271, 741))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.tabWidget = QTabWidget(self.frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 120, 251, 561))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame_4 = QFrame(self.tab)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 20, 221, 291))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.widget = QWidget(self.frame_4)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 30, 201, 124))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.operatorName = QLineEdit(self.widget)
        self.operatorName.setObjectName(u"operatorName")

        self.verticalLayout.addWidget(self.operatorName)

        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout.addWidget(self.label_3)

        self.operatorCode = QLineEdit(self.widget)
        self.operatorCode.setObjectName(u"operatorCode")

        self.verticalLayout.addWidget(self.operatorCode)

        self.operatorNext = QPushButton(self.widget)
        self.operatorNext.setObjectName(u"operatorNext")

        self.verticalLayout.addWidget(self.operatorNext)

        self.timeEdit = QTimeEdit(self.tab)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(60, 640, 118, 22))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 221, 101))
        self.label_4.setPixmap(QPixmap(u":/images/logo.png"))
        self.cRepeatTest = QFrame(self.centralwidget)
        self.cRepeatTest.setObjectName(u"cRepeatTest")
        self.cRepeatTest.setGeometry(QRect(290, 20, 891, 741))
        self.cRepeatTest.setFrameShape(QFrame.StyledPanel)
        self.cRepeatTest.setFrameShadow(QFrame.Raised)
        self.tabTest = QTabWidget(self.cRepeatTest)
        self.tabTest.setObjectName(u"tabTest")
        self.tabTest.setGeometry(QRect(10, 20, 861, 671))
        self.Test1 = QWidget()
        self.Test1.setObjectName(u"Test1")
        self.label = QLabel(self.Test1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 500, 601, 111))
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        self.tabTest.addTab(self.Test1, "")
        self.Test2 = QWidget()
        self.Test2.setObjectName(u"Test2")
        self.tabTest.addTab(self.Test2, "")
        self.Test3 = QWidget()
        self.Test3.setObjectName(u"Test3")
        self.tabTest.addTab(self.Test3, "")
        self.cNextTest = QPushButton(self.cRepeatTest)
        self.cNextTest.setObjectName(u"cNextTest")
        self.cNextTest.setGeometry(QRect(530, 700, 141, 31))
        self.pushButton = QPushButton(self.cRepeatTest)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 700, 131, 31))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(1200, 20, 231, 741))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.tabWidget_3 = QTabWidget(self.frame_3)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(10, 20, 201, 711))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget_3.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1442, 30))
        self.menuSql = QMenu(self.menubar)
        self.menuSql.setObjectName(u"menuSql")
        self.menuTechnical_View = QMenu(self.menubar)
        self.menuTechnical_View.setObjectName(u"menuTechnical_View")
        self.menuQuit = QMenu(self.menubar)
        self.menuQuit.setObjectName(u"menuQuit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuSql.menuAction())
        self.menubar.addAction(self.menuTechnical_View.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menuSql.addAction(self.actionSave)
        self.menuSql.addAction(self.actionopen)
        self.menuSql.addAction(self.actionOpen)
        self.menuTechnical_View.addAction(self.actionOperator)
        self.menuTechnical_View.addAction(self.actionTechnician)
        self.menuQuit.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionOperator)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTechnician)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        self.tabTest.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen.setText(QCoreApplication.translate("MainWindow", u"save as", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionOperator.setText(QCoreApplication.translate("MainWindow", u"Operator", None))
        self.actionTechnician.setText(QCoreApplication.translate("MainWindow", u"Technician", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+Q", None))
#endif // QT_CONFIG(shortcut)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"operator Name", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"operator Code", None))
        self.operatorNext.setText(QCoreApplication.translate("MainWindow", u"save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.label_4.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"instructions test 1", None))
        self.tabTest.setTabText(self.tabTest.indexOf(self.Test1), QCoreApplication.translate("MainWindow", u"Test 1", None))
        self.tabTest.setTabText(self.tabTest.indexOf(self.Test2), QCoreApplication.translate("MainWindow", u"Test 2", None))
        self.tabTest.setTabText(self.tabTest.indexOf(self.Test3), QCoreApplication.translate("MainWindow", u"Test 3", None))
        self.cNextTest.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Repeat", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.menuSql.setTitle(QCoreApplication.translate("MainWindow", u"Sql", None))
        self.menuTechnical_View.setTitle(QCoreApplication.translate("MainWindow", u"Technical View", None))
        self.menuQuit.setTitle(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

